version: '3.9'

services:
  backend:
    image: mrjaguar/myapp-backend:latest
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
        mode: ingress
    networks:
      - ci_cd_pipeline

networks:
  ci_cd_pipeline:
    driver: overlay