version: '3.9'

services:
  backend:
    image: mrjaguar/myapp-backend:latest
    deploy:
      replicas: 3
    networks:
      - webnet
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
        mode: ingress

networks:
  webnet:
    driver: overlay